### ISSUE TITLE
Find new modulation effects, phaser and chorus

### ISSUE THREAD

**Issue by pauljonescodes** [pauljonescodes/supertonal#17]

**Comment by corybergeron** [comment]
I haven't had much (and by much I mean none) with these modulation effects. I know we lifted these ones from BYOD. I think it may be worthwhile to see what other choruses/phasers are out there in the community. I'd even be interested in exploring other reverb options. The current one isn't bad... but it doesn't get me stoked and I think I would probably not use it in a real mix application.
