### ISSUE TITLE
EQ HPF + LPF: Q default value = "0"

### ISSUE THREAD

**Issue by corybergeron** [pauljonescodes/supertonal#26]

**Comment by pauljonescodes** [comment]
Quality can't truly be 0 on JUCE's system, but they should already be 0.001 

https://github.com/pauljonescodes/supertonal/blob/1070323499e170106cd9d5f6a2c04a220321142c/Source/PluginAudioParameters.h#L215

![image](https://github.com/pauljonescodes/supertonal/assets/1176952/2f539f20-4ee3-420c-94ea-bd086b3ae16b)

**Comment by corybergeron** [comment]
I'm an idiot. I meant to write that it should default to "1"
